# Configuraton File #
#===================#
title: Jekyll Arabica Boilerplate
email: sricharan.krishnan@gmail.com
github_username: sricharankrishnan (https://github.com/sricharankrishnan/)

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Expect the following details to be excluded during the final build process
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - package.json
   - package-lock.json

# Handling Permalinks.
permalink: /:categories/:title/

sass:
  style: compressed

# Default Front Matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      title: "Sricharan Krishnan | Software Developer"
      metaDescription: "The Aspiring Builder/Student of the Art of Code/Developer Underdog/"
      metaKeywords: "sricharan krishnan, sricharan, aspiring builder, developer underdog, builder"

